src/Entity/Property.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @UniqueEntity("title")
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @Vich\Uploadable()
 */
class Property
{


    const HEAT = [

        0 => 'Gaz',
        1 => 'Bois',
        2 => 'Electrique'
      
    ];


    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @var string|null
     * @orm\column(type="string", length=255)
     */
    private $filename;

    /**
     * @var File|null
     * @Assert\Image(
     *     mimeTypes="image/jpeg"
     * )
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $prince;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @Assert\Regex("/^[0-9]{5}$/")

     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default":false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Opt", inversedBy="properties")
     */
    private $opts;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;


    

 

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->opts = new ArrayCollection();
       
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrince(): ?int
    {
        return $this->prince;
    }

    public function setPrince(int $prince): self
    {
        $this->prince = $prince;

        return $this;
    }

    public function getFormattedPrince(): string
    {
       return number_format( $this->prince,'0', '', ' ' );  
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function getHeatType(): ?string
    {
        return self::HEAT[$this->heat] ;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Opt[]
     */
    public function getOpts(): Collection
    {
        return $this->opts;
    }

    public function addOpt(Opt $opt): self
    {
        if (!$this->opts->contains($opt)) {
            $this->opts[] = $opt;
            $opt->addProperty($this);
        }

        return $this;
    }

    public function removeOpt(Opt $opt): self
    {
        if ($this->opts->contains($opt)) {
            $this->opts->removeElement($opt);
            $opt->removeProperty($this);
        }

        return $this;
    }

    /**
     * @return string|null
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param string|null $filename
     */
    public function setFilename(?string $filename): void
    {
        $this->filename = $filename;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     */
    public function setImageFile(?File $imageFile): void
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTime('now');
        }
    }
    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

   
 
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Opt;
use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('prince')
            ->add('heat',ChoiceType::class,[
                 'choices' => array(
                    'Gaz' => '0',
                    'Bois' => '1',
                    'Electrique' => '2')
            ])
            ->add('opts', EntityType::class,[
                'class' => Opt::class,
                'required' => false,
                'choice_label' => 'name',
                'multiple' => true

            ])
            ->add('imageFile', FileType::class,[
                'required' => false
            ])
            ->add('city')
            ->add('adress')
            ->add('postal_code')
            ->add('sold')
            ->add('Enregistrer', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
        ]);
    }

}

src/Controller/PropertyController.php
<?php
namespace App\Controller;

use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Repository\PropertyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Common\Persistence\ObjectManager;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;




 class PropertyController extends AbstractController
 {
     
   public function __construct(PropertyRepository $repository, ObjectManager $em)
   {
      $this->repository = $repository;
      $this->em = $em;
   }


    /**
 * @route("/biens", name="property.index")
 * @return Response
 */

   public function index(Request $request, PaginatorInterface $paginator) // Nous ajoutons les paramètres requis
   {
      $search = new PropertySearch;
      $form = $this->createform(PropertySearchType::class, $search);
      $form->handleRequest($request);
       // Méthode findBy qui permet de récupérer les données avec des critères de filtre et de tri
       $donnees = $this->getDoctrine()->getRepository(Property::class)->findAllVisibleQuery($search);

       $properties = $paginator->paginate(
           $donnees, // Requête contenant les données à paginer (ici nos articles)
           $request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
           6 // Nombre de résultats par page
       );
       
       return $this->render('property/index.html.twig', [
         'current_menu' => 'properties',
               'properties' => $properties,
               'form' => $form->createview()
       ]);
   }


   /**
 * @route("/biens/{slug}-{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*"})
 * @param  Property $property
 * @return Response
 */

 public function show(Property $property,string $slug): Response
 {
    if ($property->getslug() !== $slug)
    {
      return $this->redirectToRoute('property.show', [
         'id' => $property->getId(),
         'slug' => $property->getSlug()
      ], 301);
    }
   return $this->render('property/show.html.twig', [
      'property' => $property,
      'current_menu' => 'properties'

   ]);
 }
 }

templates/property/_property.html.twig
<div class="card mb-4" >
    {% if property.filename %}
        <img src="{{ vich_uploader_asset(property , 'imageFile') | imagine_filter('thumb') }}" alt="card-img-top" style="width: 300px; height: 150px;">
    {% endif %}
<div class="card-body">


<h5 class="card-title">

<a href="{{ path('property.show', {slug: property.slug, id: property.id}) }}">
{{ property.title}}
</a>
</h5>
<p class="card-text">{{ property.surface }}M2 {{ property.city }} {{ property.postalCode }} </p>
<div class="text-primary"style= "font-size: 2em; font-weight: bold;">
{{ property.formattedPrince}} $
</div>

</div>

</div>

templates/property/index.html.twig
{%extends 'base.html.twig'%}
{%block title 'tous nos biens' %}

{% block body %}
<div class= "jumbotron text-center mt-4">
<h1> voir tous nos biens </h1>
</div>

<div class= "jumbotron text-center mt-4">
<div class= "container">
{{ form_start(form) }}

 <div class="form-row">
  <div class="col">  {{ form_row(form.minSurface) }} </div>
  <div class="col">  {{ form_row(form.maxPrince) }} </div>
  <div class="col">  {{ form_row(form.opt) }} </div>
  <div class="col">  {{ form_row(form.chercher) }} </div>
   </div>



{{ form_end(form) }}

</div>
</div>



<div class="row ml-2">
    {% for property in properties %}

<div class="col-md-4">
  


{% include "property/_property.html.twig" %} 
    

</div>


{% endfor %}
<div class="pagination">
   {{ knp_pagination_render(properties) }}
</div>


</div>

{% endblock %}
{# {% extends 'base.html.twig' %}

{% block title %}Liste des property{% endblock %}

{% block body %}
    <h1>Liste des articles</h1>
    {% for property in properties %}
      <div class="col-md-4">
  


{% include "property/_property.html.twig" %} 
    

</div>
    {% endfor %}
   <div class="pagination">
   {{ knp_pagination_render(properties) }}
</div>
{% endblock %} #}

templates/property/show.html.twig
{%extends 'base.html.twig'%}
{% block body %}



<div class="container mt-4"> 
<div class="row"> 
<div class="col-md-8">
    {% if property.filename %}
        <img src="{{ vich_uploader_asset(property , 'imageFile') | imagine_filter('medium') }}" alt="card-img-top" style="width: 100%; height: auto;">
    {% endif %}
</div>
<div class="col-md-4"> 
<h1>{{ property.title }}</h1>
<h2> {{ property.rooms}} pièces - {{ property.surface}} M2</h2>
<div class="text-primary" style="font-weight: bold; font-size: 4em">{{ property.formattedPrince }} $</div>

<a href="#" class="btn btn-primary">Contacter l'agence</a>


</div>
</div>


<p>
{{ property.description | nl2br }}
</p>
<div class="row"> 
<div class="col-md-8"> 
<h2>Caractéristiques</h2>
<table class="table table-striped">
<tr>
<td> Surface habitable </td>
<td> {{ property.surface}} M2 </td>
</tr>
<tr>
<td> Pièces </td>
<td>  {{ property.rooms}} </td>
</tr>
<tr>
<td> Chambres </td>
<td>  {{ property.bedrooms}} </td>
</tr>
<tr>
<td> Etage </td>
<td>  {{ property.floor}} </td>
</tr>
<tr>
<td> Chauffage </td>
<td>  {{ property.heatType}} </td>
</tr>
</table>

</div>
<div class="col-md-4"> 
<h2>Spécificités</h2>

<ul class="list-group">
        {% for opt in property.opts %}
            <li class="list-group-item">
                {{ opt.name }}

            </li>
        {% endfor %}

</ul>
</div>
</div>

</div>



{% endblock %}